FROM ubuntu:xenial

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends libcurl4-openssl-dev python-pip libboost-python1.58-dev libpython-dev python-setuptools libasound2-dev libpulse-dev  apt-utils swig gcc cmake build-essential  && \
    rm -rf /var/lib/apt/lists/* 

RUN pip install --upgrade pip
COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

CMD [ "python", "-u", "./main.py" ]